#!/bin/sh

mpc pause

B='#00000000'  # blank
C='#ffffff22'  # clear ish
D='#12faffdd'  # ring 
T='#30ccccee'  # text
W='#ff3d00bb'  # wrong
V='#1de9b6bb'  # verifying

i3lock \
	--insidevercolor=$C   \
	--ringvercolor=$V     \
	\
	--insidewrongcolor=$C \
	--ringwrongcolor=$W   \
	\
	--insidecolor=$C      \
	--ringcolor=$D        \
	--linecolor=$B        \
	--separatorcolor=$D   \
	\
	--verifcolor=$T       \
	--wrongcolor=$T       \
	--timecolor=$T        \
	--datecolor=$T        \
	--layoutcolor=$T      \
	--keyhlcolor=$V       \
	--bshlcolor=$W        \
	\
	--ignore-empty-password\
	--screen 1            \
	--blur 5              \
	--clock               \
	--indicator           \
	--timestr="%H:%M:%S"  \
	--datestr="%A, %m %Y" \
	--keylayout 2         \
